### ISSUE TITLE
Unreal5.4 project creates a new module error

### ISSUE THREAD

**Issue by andiven** [AskingQuestions/Shadeup#18]
When creating a new module in an Unreal 5.4 project, the following error is displayed:
```
Error: Failed to parse plugin file. Please make sure it is a valid JSON file. 
at CreateModule (@shadeup/unreal/cli.js:119:9) 
at IQModuleFolder (@shadeup/unreal/cli.js:232:25) 
at process.processTicksAndRejections (node/process/task_queues:105:5) 
at async IQModuleFolder (@shadeup/unreal/cli.js:207:10) 
at async IQModuleFolder (@shadeup/unreal/cli.js:207:10) 
at async IQModuleFolder (@shadeup/unreal/cli.js:207:10) 
at async IQModuleFolder (@shadeup/unreal/cli.js:207:10) 
at async IQModuleFolder (@shadeup/unreal/cli.js:207:10) 
at async IQModuleFolder (@shadeup/unreal/cli.js:207:10) 
at async IQModuleFolder (@shadeup/unreal/cli.js:207:10)
```

**Comment by andrewpros** [comment]
The issue is due to parent plugin .uplugin file being UTF8 with BOM, convert to UTF8 without BOM with notepad++ and it will work.
